name: tourism_app
description: A new Flutter project for tourism.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to a common modern range

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0 # Use latest compatible versions
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^1.2.1
  intl: ^0.19.0 # Common version, adjust if needed
  uuid: ^4.3.3 # For dummy data service

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Or ^2.0.0 if issues arise

flutter:
  uses-material-design: true
